# Generated by Django 3.1.6 on 2021-02-08 14:58

from django.db import migrations, models


def prefill_db(apps, schema_editor):
    Slot = apps.get_model('slot', 'Slot')
    Slot.objects.bulk_create([Slot(time=f'0{i}:00') for i in range(10)])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('time', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RunPython(prefill_db),
    ]
