replicaCount: 2

image:
  repository: msergei/crud-server
  check_db: postgres:alpine

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - /otusapp/mironov($|/)(.*)
      serviceName: crud-service

postgresql:
  enabled: true
  postgresqlHost: "postgres"
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  servicePort: 5432
