version: '3.6'

volumes:
  psql: {}

services:

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    env_file:
      - db.env

  crud:
    build: .
    image: msergei/crud-server
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    links:
      - db:postgres
    env_file:
      - db.env
