{
 "title": "The final project dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Django RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_requests_total_by_view_transport_method_total[1m]))"
    }
   ]
  },
  {
   "title": "Django Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Response 200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Django Response 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "Django Response 404",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"404\"}[1m]))"
    }
   ]
  }
 ]
}