{
 "title": "My test dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Postgre Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Postgre Databases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size)"
    }
   ]
  },
  {
   "title": "Postgre rotation size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_settings_log_rotation_size_bytes"
    }
   ]
  },
  {
   "title": "Postgre Max WAL Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_max_wal_size_bytes" }
   ]
  },
  {
   "title": "Postgre Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_work_mem_bytes" }
   ]
  },
  {
   "title": "Postgres SELECT per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_tup_fetched[1m]))"
    }
   ]
  },
  {
   "title": "Postres Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_commit[1m]))",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_rollback[1m]))",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Nginx Response 200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Response 50x",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"502\"}[1m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"503\"}[1m]))",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "Nginx Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, status) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Nginx Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, status) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Nginx Latency Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, status) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Nginx Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, status) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Django Latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Django Response 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "Django Response 404",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"404\"}[1m]))"
    }
   ]
  },
  {
   "title": "Django Response 201",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_responses_total_by_status_view_method_total{status=\"201\"}[1m]))"
    }
   ]
  },
  {
   "title": "Django RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_requests_total_by_view_transport_method_total[1m]))"
    }
   ]
  }
 ]
}