apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-config
data:
  POSTGRES_DB: user-crud
  POSTGRES_USER: user-crud
  PSQL_HOST: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: crud-secret
type: Opaque
data:
  POSTGRES_PASSWORD: bXktc3VwZXItcGFzc3dvcmQ=
