apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
    spec:
      restartPolicy: Never
      containers:
      - name: migrate-job
        envFrom:
          - configMapRef:
              name: crud-config
          - secretRef:
              name: crud-secret
        image: msergei/crud-server:0.2
        command:
          - sh
          - "-c"
          - |
            echo 'postgres waiting';
            sleep 60s;
            ./manage.py migrate;
