# Generated by Django 3.1.6 on 2021-02-08 14:17

from django.db import migrations, models


def prefill_db(apps, schema_editor):
    Item = apps.get_model('item', 'Item')
    Item.objects.bulk_create([Item(name=f'Item{i}') for i in range(10)])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RunPython(prefill_db)
    ]
