# Generated by Django 3.1.5 on 2021-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
