version: '3.6'

volumes:
  auth_psql: {}
  profiles_psql: {}

services:

  auth_db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - auth_psql:/var/lib/postgresql/data
    env_file:
      - auth/db.env
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/lib/postgresql/data/ready" ]
      interval: 10s
      timeout: 10s
      retries: 100

  auth:
    build:
      context: ./auth/
    image: msergei/auth-service:v0.3
    command: sh -c "./manage.py migrate && gunicorn uauth.wsgi -b 0.0.0.0:8000 --workers=4 --timeout 10;"
    ports:
      - 8000:8000
    volumes:
      - ./auth/:/app/
    links:
      - auth_db:postgres
      - profiles:profiles
    env_file:
      - auth/db.env
    depends_on:
      - profiles

  profiles_db:
    image: postgres:alpine
    ports:
      - 5433:5432
    volumes:
      - profiles_psql:/var/lib/postgresql/data
    env_file:
      - profiles/db.env
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/lib/postgresql/data/ready" ]
      interval: 10s
      timeout: 10s
      retries: 100

  profiles:
    build:
      context: ./profiles/
    image: msergei/profiles-service:v0.3
    command: sh -c "sleep 10; ./manage.py migrate && gunicorn profiles.wsgi -b 0.0.0.0:8000 --workers=4 --timeout 10;"
    ports:
      - 8001:8000
    volumes:
      - ./profiles/:/app/
    links:
      - profiles_db:postgres
    env_file:
      - profiles/db.env
