version: '3.6'

volumes:
  psql: {}

services:

  auth_db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    env_file:
      - db.env
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/lib/postgresql/data/ready" ]
      interval: 5s
      timeout: 10s
      retries: 100

  web:
    build: .
    image: uauth
    container_name: auth_service
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    links:
      - auth_db:postgres
    env_file:
      - db.env
