# Generated by Django 3.1.6 on 2021-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('details', models.JSONField()),
                ('success', models.BooleanField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
